# This script copies blog posts from the static dump from pt14
# (generated by _dump.sh) and formats the posts in a way appropriate
# for Jekyll. Note that this process is not fully automated, as the
# original posts contain a large amount of cruft which must be
# separated from the content itself.

# Requirements:
#
#  * Run _dump.sh first
#  * Pandoc (http://johnmacfarlane.net/pandoc/)
#  * A reasonably Unixy environment with bash, iconv, etc.

for f in $(find pt14 -path 'pt14/20*' -name 'index.html' -mindepth 5 -maxdepth 5); do
  y=$(basename $(dirname $(dirname $(dirname $(dirname $f)))))
  m=$(basename $(dirname $(dirname $(dirname $f))))
  d=$(basename $(dirname $(dirname $f)))
  t=$(basename $(dirname $f))
  cat > _posts/$y-$m-$d-$t.md <<EOF
---
title:
author:
---

EOF
  pandoc --atx-headers -f html -t markdown-raw_html $f | iconv -f UTF-8 -t ASCII//TRANSLIT >> _posts/$y-$m-$d-$t.md
done
